### ISSUE TITLE
TypeError: no implicit conversion of Array into String

### ISSUE THREAD

**Issue by txapelgorri** [andec/i2c#5]
What I'm trying:

``` ruby
require 'i2c'
i2c = I2C.create('/dev/i2c-1')
mcp = I2C::Drivers::MCP23017.new(i2c,0x20)
```

and I get:

`TypeError: no implicit conversion of Array into String` at file `lib/i2c/backends/i2c-dev.rb:31:in block in write` with Ruby 2.1.10.

I found on that file that there is a `data << value` assignation, when data is defined as string in line # 28 :/

**Comment by andec** [comment]
Just commited a fix. I am not actually sure it works, though. I have no test equipment available currently.
