### ISSUE TITLE
Update Gemspec and push gem

### ISSUE THREAD

**Issue by Xasin** [andec/i2c#8]
I just checked, and the current version of the i2c gem found on rubygems.org is a little outdated, as it is from 2015.
I recommend testing the gem, updating the gemspec's version and then publishing a fresh version ^^

**Comment by andec** [comment]
Yes, you are right, that should be done. I have to admit I mostly lost interest in the code and keep maintenance to a minimum. Do you have any interest in maintaining the code?

**Comment by Xasin** [comment]
@andec, if you're ok with it I could do that!
I don't expect the drivers will change much in the future, so I hope maintenance will mostly be ironing out bugs in the rest of the code.

But I do think I have the necessary knowledge to properly continue work - Testing, Rubygems and documentation, etc.

**Comment by andec** [comment]
@Xasin Thank you. I was not actively using the lib in years and am happy to see an actual user continuing the work.

**Comment by andec** [comment]
Ah, yes. Did that too. You should have access.
