### ISSUE TITLE
initialisation of MCP23017 corrupts data

### ISSUE THREAD

**Issue by falkorichter** [andec/i2c#9]
We have a MCP23017 attached to a Raspberry Pi compute module.

The device is setup to use address 0x23. We have the reset pin also wired to the Pi.

As a reference we use the two methods to read `input` values of the device. Python and direct shell

We read after the device is reset. As per datasheet it is therefore initialised to `input`
```
i2cget -y 1 0x23 0x12
i2cget -y 1 0x23 0x13
```
and we get the values as expected.

Also with python:
```
#!/usr/bin/python

import smbus
import time
import sys

bus = smbus.SMBus(1) # Rev 2 Pi uses 1

DEVICE = 0x23 # Device address (A0-A2)

GPIOA  = 0x12 # Register for inputs
GPIOB  = 0x13 # Register for inputs

stateBankA = bus.read_byte_data(DEVICE,GPIOA)
stateBankB = bus.read_byte_data(DEVICE,GPIOB)

print "state of the GPIO " + bin(stateBankA) + bin(stateBankB)
```

When a signal is attached to pin 16 we read:
```
0x00
0x80
```
same with the python script:
```
state of the GPIO 0b00b10000000
```

And it reacts accordingly when I provide a signal to another pin.

We wrote a little ruby script to also read the input values. Our business logic is also written in Ruby so this is the prototype of the final implementation:

```
#!/usr/bin/env ruby

require 'i2c'

mcp = I2C::Drivers::MCP23017.new("/dev/i2c-1", 0x23)
#(0..15).each do |pin|
#   mcp.mode(pin, INPUT)
#end
(0..15).each do |pin|
   print "#{mcp[pin]}"
end
print "/n"
```
First issue: The default state when reading via ruby is not `0000000000000000` but it is `0000000011111111`. There is no input signal. When providing an input to pin 16 the output is `0000000011111110`.
The issue is present both when setting the mode or not.

**Why is the second bank inverted?**

Second issue: After running the ruby script once, also the output in python and shell is "corrupted".

```
0x00
0x7f
```
is now the output of the shell script
`state of the GPIO 0b00b1111111` is the output of the Python script.

`state of the GPIO 0b00b11111111` is the output with input signal.

I looked in the initialisation and saw there is some writing when doing the initialisation:
https://github.com/andec/i2c/blob/master/lib/i2c/drivers/mcp230xx.rb#L54

I'm trying to make some sense of the reading in the `irb`. I don't understand how to do a simple `i2cget -y 1 0x23 0x12`would translate to the ruby code:
```
irb(main):025:0> device.read(0x23,2,0x12).unpack('CC')
=> [0, 128]
irb(main):026:0> device.read(0x23,1,0x12).unpack('CC')
=> [0, nil]
```
output of `i2cget`remains to be 
```
0x00
0x80
```

**Comment by Xasin** [comment]
When you use the i2c-get command, it looks like it's reading one byte only - that would be 0x00 on the first read, then 0x80 on the second.
When you issue `device.read(0x23, 2, 0x12)`, you read two bytes - those are returned as 0x00 and 0x80 (or 128 in decimal) - thusly, they're exactly the same as the i2cget command.
The second read command you issue re-sends the "0x12" command byte to the device, however then only reads a single byte (as you specify), which is just the zero.

I haven't written the MCP driver code myself, but I suppose I could have a look at it and see if there's something broken. The inversion of the second register kind of suggests so, but it could also be that a register on the MCP is set that messes some stuff up.
